namespace VoxScope.Presets;

public sealed record Preset(
    string Name,
    float PitchShiftSemitones,
    int PitchShiftStageMode,
    float FormantShiftSemitones,
    bool HighBandArtifactReducerEnabled,
    float HighBandArtifactReducerMaxReductionDb,
    bool PostPitchCorrectionEqEnabled,
    float PostPitchCorrectionEqStrength,
    bool PostPitchDeEsserEnabled,
    float PostPitchDeEsserMaxReductionDb,
    bool PostPitchSmoothingCompressorEnabled,
    float PostPitchSmoothingCompressorStrength,
    float OutputGainDb,
    bool NoiseGateEnabled,
    float NoiseGateThresholdDb,
    bool CompressorEnabled,
    float CompressorThresholdDb,
    float CompressorRatio,
    float CompressorMakeupGainDb,
    float EqLowGainDb,
    float EqMidGainDb,
    float EqHighGainDb)
{
    public static Preset Default { get; } = new(
        "Default",
        0f,
        0,
        0f,
        true,
        6f,
        true,
        0.35f,
        true,
        6f,
        true,
        0.35f,
        0f,
        false,
        -45f,
        false,
        -18f,
        3f,
        0f,
        0f,
        0f,
        0f);
}
